---
# tasks/main.yml

- name: Include platform specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_extension_conf_paths
  set_fact:
    php_extension_conf_paths: "{{ __php_extension_conf_paths }}"
  when: php_extension_conf_paths is not defined
  
- name: Define php_mcrypt_config_filename
  set_fact:
    php_mcrypt_config_filename: "{{ __php_mcrypt_config_filename }}"
  when: php_mcrypt_config_filename is not defined

- name: Install php-mcrypt package (RedHat)
  yum:
    name: ["php-mcrypt"]
    state: present
    enablerepo: "{{ __php_enablerepo }}"
  when: ansible_os_family == 'RedHat'

- name: Ensure dependencies are installed (Debian)
  apt:
    name: "{{ item }}"
    name: ["build-essential", "autoconf", "pkg-config", "php{{ __php_version }}-dev", "libmcrypt-dev", "php-pear"]
    state: present
  when: ansible_os_family == 'Debian'

- name: Install mcrypt pecl package (Debian)
  shell: "yes '' | pecl install mcrypt-{{ mcrypt_version }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  when: ansible_os_family == 'Debian'

#- name: Install mcrypt pecl package (Debian)
#  pear:
#    name: "mcrypt-{{ mcrypt_version }}"
#    state: present
#  when: ansible_os_family == 'Debian'

- import_tasks: configure.yml
